import { Cabin } from "next/font/google";
import CursorGlowEffect from "@/components/ui/CursorGlowEffect";
import "./globals.css";

const cabin = Cabin({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cabin.className}`}>
        <CursorGlowEffect />
        {children}
      </body>
    </html>
  );
}
